### ISSUE TITLE
Missing query flags

### ISSUE THREAD

**Issue by tansawit** [skip-mev/connect#119]
Currently, Slinky CLI commands doesn't query flags. For example, attempting to run the command:
```
initiad query oracle currency-pairs --node <INITIA_RPC_URL>
```

Results in the following error message:
```sh
Error: unknown flag: --node
Usage:
  initiad query oracle currency-pairs [flags]
```
The problem seems to be from in the CLI commands defined in the various Slinky module ﻿query.go files – such as [this one](https://github.com/skip-mev/slinky/blob/f1b58a03250e301b54467a5e5563f024e58ef221/x/oracle/client/cli/query.go). These definitions currently fail to support query flags that are added through ﻿flags.AddQueryFlagsToCmd(cmd).

h/t @beer-1 for identifying the issue/necessary changes

**Comment by Eric-Warehime** [comment]
Thanks for submitting this issue! I've opened https://github.com/skip-mev/slinky/pull/120 to resolve this.

**Comment by tansawit** [comment]
Thanks for the quick response!

**Comment by Eric-Warehime** [comment]
No problem, PR is merged. If you're trying to use it on initia it won't start working until we've put this into a release and updated the initia binary with it.
