### ISSUE TITLE
Can't fetch Coinbase data at Initia testnet

### ISSUE THREAD

**Issue by yanglaolee** [skip-mev/connect#449]
As I said in the title：
![屏幕截图 2024-05-24 113649](https://github.com/skip-mev/slinky/assets/107319060/bd6c1461-4464-4e8b-aeb2-5d421289576f)

**Comment by davidterpay** [comment]
hey @yanglaolee, you can follow this PR here where we are replacing the REST implementation of Coinbase with the WebSocket implementation https://github.com/skip-mev/slinky/pull/448. This should resolve the issue you are having.

**Comment by yanglaolee** [comment]
> hey @yanglaolee, you can follow this PR here where we are replacing the REST implementation of Coinbase with the WebSocket implementation #448. This should resolve the issue you are having.

Sure, I'm following it
