### ISSUE TITLE
Proposal: have a command that generates default config, but do not run when it's not present.

### ISSUE THREAD

**Issue by freak12techno** [skip-mev/connect#505]
We faced an issue when preparing the pion-1 upgrade on Cosmos Incentivised Testnet that it's unclear where the default oracle.json is generated, and having it auto-generated is less explicit and gives you less control over the app's configuration

I propose to do it the way cosmos-sdk does it:
- have a command (let's say `slinky init`) that generates a default `oracle.json` in some directory (I suggest `~/.slinky` similarly to how cosmos-sdk does it)
- the `slinky` binary, when run without arguments, fetches the `oracle.json` file from the slinky folder (also defaults to `~/.slinky`) and crashes if it's not present

That way, those running slinky would have more clarity over slinky's config and would have more control and awareness over it.

What do you think?

**Comment by g3ndo9kar9** [comment]
@freak12techno we really appreciate the feedback!

We originally had a flow to what you're suggesting, i.e
1. Run `slinky-config` to generate an `oracle.json` file that operators can modify
2. Run `slinky` pointing at your generated config

We found that this method was challenging for operators, as the generated config file is v large (1000s of json LOC). It was also v easy to mess smth up, and hard to debug. Finally, we found many operators copy/pasting configs that existed elsewhere, leading to their slinky instances not working as expected.

Hence we've moved to having the default configs embedded w/in the `slinky` binary, and allowing operators to easily over-ride specific values, see [here](https://docs.skip.money/slinky/validator/validator-slinky-config) for details. 

Would the configuration process linked above help at all? Or would you still prefer to have the entire config generated / output somewhere for you to modify?

**Comment by freak12techno** [comment]
@nivasan1 what do you think of leaving the default behaviour (like, running without config using the in-memory one if that's not provided) but adding a command that will generate the config and write it into a file (like `slinky init`)? That should preserve the behaviour, leaving the default one as it is now, while allowing operators to have more granular control on what they are running.

Also I wonder what's your thought about having a home folder (like ~/.slinky), taking config from there if it's present (like ~/.slinky/config.json) and requiring the home folder path (and defaulting it to ~/.slinky) instead of providing the full config path for every file Slinky requires? IMO it's a win-win as it will also allow to store all Slinky configs in one folder and allowing only specifying it once instead of multiple times (for example, logs can go there as well) but maybe there are some caveats I have not considered.

**Comment by aljo242** [comment]
@freak12techno right now the `Connect` binary will just run with a default config that can be overrwritten with flags.

We've removed the `slinky-config` util entirely and have a much simpler process
