### ISSUE TITLE
The system cannot find the file specified issue when running make command

### ISSUE THREAD

**Issue by GitBolt** [skip-mev/connect#758]
![Untitled](https://github.com/user-attachments/assets/a797b5dc-9f9c-46ce-896c-7980fcc99f99)

- System: Windows 11
- LLVM & Go are installed
- Running on commit 7106b2bd

**Comment by aljo242** [comment]
Hi @GitBolt - we don't support running on Windows

**Comment by aljo242** [comment]
Closing this for now - we have no plans to support running on Windows
