### ISSUE TITLE
Oracle config schema has no docs, no example in repo, no code to generate

### ISSUE THREAD

**Issue by danielkokobt** [skip-mev/connect#761]
The only way to find the oracle config schema in recent releases is by reading the code.

Older versions provided an example file in the repo, but the file is no longer included and the schema has since changed.

[connect/oracle/README.md](https://github.com/skip-mev/connect/blob/c922740f0c7f667bbe3fd40b22f69900d2649105/oracle/README.md) states that the oracle config is documented in connect/oracle/config/README.md, but that file does not exist.

**Comment by aljo242** [comment]
@danielkokobt linked a PR to address this - thanks for raising this issue
